version: "3.3"

services:
  server:
    image: chaskiq/chaskiq:latest
    restart: always
    ports:
      - 172.17.0.1:6734:3000
    env_file:
      - ./.env
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
      - ./localstorage:/usr/src/app/datastorage
    depends_on:
      - db
      - redis

  worker:
    image: chaskiq/chaskiq:latest
    restart: always
    env_file:
      - ./.env
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis

  db:
    image: elestio/postgres:15
    ports:
      - "172.17.0.1:5822:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_DB: chaskiq
    volumes:
      - ./storage/pgdata:/var/lib/postgresql/data/

  redis:
    image: elestio/redis:7.0
    restart: always
    env_file:
      - ./.env
    volumes:
      - "./storage/redis-data:/data"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:8869:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
